# Generated by Django 3.0.5 on 2020-05-12 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteTutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data envio'),
            preserve_default=False,
        ),
    ]
